In [79]:
import numpy as np


def matrix2latex(A: np.array, n: int = 4):
    n, m = A.shape[:2]
    newline = r' \\ '
    command = f"""
        \\left[\\begin{{array}}{{{"c"*m}}}
            {(newline.join(" & ".join('{:{}g}'.format(A[i][j], n) for j in range(m)) for i in range(n)))}
        \\end{{array}}\\right]
    """
    return command

print(matrix2latex(np.zeros((3, 5))))



        \left[\begin{array}{ccccc}
              0 &   0 &   0 &   0 &   0 \\   0 &   0 &   0 &   0 &   0 \\   0 &   0 &   0 &   0 &   0
        \end{array}\right]
    


In [35]:
def valid_n(n: int):
    valid_number_n = lambda x : float(np.format_float_scientific(x, n, True))
    return np.vectorize(valid_number_n)

def round_n(n: int):
    valid_number_n = lambda x : round(x, n)
    return np.vectorize(valid_number_n)

f = valid_n(3 - 1)
A = np.random.random((4, 4)) * 5
print(A)
print(f(A))

[[0.07166648 1.52931806 3.24033653 0.95701732]
 [4.30858282 4.69666905 4.1093449  4.61480882]
 [1.43128065 2.77389739 2.85786731 1.69766613]
 [2.32362252 0.22160706 2.05932556 2.27741496]]
[[0.0717 1.53   3.24   0.957 ]
 [4.31   4.7    4.11   4.61  ]
 [1.43   2.77   2.86   1.7   ]
 [2.32   0.222  2.06   2.28  ]]


In [45]:
A = np.array([
    [0.4096, 0.1234, 0.3678, 0.2943],
    [0.2246, 0.3872, 0.4015, 0.1129],
    [0.3645, 0.1920, 0.3781, 0.0643],
    [0.1784, 0.4002, 0.2786, 0.3927]
])
b = np.array([
    [0.4043],
    [0.1550],
    [0.4240],
    [-0.2557]
])
print(A)
print(b)
commandA = matrix2latex(A)
commandb = matrix2latex(b)
print(commandA, commandb)

[[0.4096 0.1234 0.3678 0.2943]
 [0.2246 0.3872 0.4015 0.1129]
 [0.3645 0.192  0.3781 0.0643]
 [0.1784 0.4002 0.2786 0.3927]]
[[ 0.4043]
 [ 0.155 ]
 [ 0.424 ]
 [-0.2557]]

        \begin{array}{cccc}
            0.4096 & 0.1234 & 0.3678 & 0.2943 \\ 0.2246 & 0.3872 & 0.4015 & 0.1129 \\ 0.3645 & 0.192 & 0.3781 & 0.0643 \\ 0.1784 & 0.4002 & 0.2786 & 0.3927
        \end{array}
     
        \begin{array}{c}
            0.4043 \\ 0.155 \\ 0.424 \\ -0.2557
        \end{array}
    


In [46]:
R = np.array([
    [1., 0., 0., 0.],
    [-A[1][0] / A[0][0], 1., 0., 0.],
    [-A[2][0] / A[0][0], 0., 1., 0.],
    [-A[3][0] / A[0][0], 0., 0., 1.]
])

f = round_n(4)
R = f(R)

print(R)
print(matrix2latex(R))

A2 = f(R @ A)
b2 = f(R @ b)

print(A2)
print(b2)
print(matrix2latex(A2))
print(matrix2latex(b2))

[[ 1.      0.      0.      0.    ]
 [-0.5483  1.      0.      0.    ]
 [-0.8899  0.      1.      0.    ]
 [-0.4355  0.      0.      1.    ]]

        \begin{array}{cccc}
               1 &    0 &    0 &    0 \\ -0.5483 &    1 &    0 &    0 \\ -0.8899 &    0 &    1 &    0 \\ -0.4355 &    0 &    0 &    1
        \end{array}
    
[[ 0.4096  0.1234  0.3678  0.2943]
 [ 0.      0.3195  0.1998 -0.0485]
 [-0.      0.0822  0.0508 -0.1976]
 [ 0.      0.3465  0.1184  0.2645]]
[[ 0.4043]
 [-0.0667]
 [ 0.0642]
 [-0.4318]]

        \begin{array}{cccc}
            0.4096 & 0.1234 & 0.3678 & 0.2943 \\    0 & 0.3195 & 0.1998 & -0.0485 \\   -0 & 0.0822 & 0.0508 & -0.1976 \\    0 & 0.3465 & 0.1184 & 0.2645
        \end{array}
    

        \begin{array}{c}
            0.4043 \\ -0.0667 \\ 0.0642 \\ -0.4318
        \end{array}
    


In [49]:
R2 = np.array([
    [1., 0., 0., 0.],
    [0., 1., 0., 0.],
    [0., -A2[2][1] / A2[1][1], 1., 0.],
    [0., -A2[3][1] / A2[1][1], 0., 1.]
])
# print(R2)
R2 = f(R2)
print(R2)

print(matrix2latex(R2))

A3 = f(R2 @ A2)
b3 = f(R2 @ b2)
print(A3)
print(b3)
print(matrix2latex(A3))
print(matrix2latex(b3))

[[ 1.      0.      0.      0.    ]
 [ 0.      1.      0.      0.    ]
 [ 0.     -0.2573  1.      0.    ]
 [ 0.     -1.0845  0.      1.    ]]

        \begin{array}{cccc}
               1 &    0 &    0 &    0 \\    0 &    1 &    0 &    0 \\    0 & -0.2573 &    1 &    0 \\    0 & -1.0845 &    0 &    1
        \end{array}
    
[[ 0.4096  0.1234  0.3678  0.2943]
 [ 0.      0.3195  0.1998 -0.0485]
 [ 0.     -0.     -0.0006 -0.1851]
 [ 0.      0.     -0.0983  0.3171]]
[[ 0.4043]
 [-0.0667]
 [ 0.0814]
 [-0.3595]]

        \begin{array}{cccc}
            0.4096 & 0.1234 & 0.3678 & 0.2943 \\    0 & 0.3195 & 0.1998 & -0.0485 \\    0 &   -0 & -0.0006 & -0.1851 \\    0 &    0 & -0.0983 & 0.3171
        \end{array}
    

        \begin{array}{c}
            0.4043 \\ -0.0667 \\ 0.0814 \\ -0.3595
        \end{array}
    


In [50]:
R3 = np.array([
    [1., 0., 0., 0.],
    [0., 1., 0., 0.],
    [0., 0., 1., 0.],
    [0., 0., -A3[3][2] / A3[2][2], 1.]
])
# print(R2)
R3 = f(R3)
print(R3)

print(matrix2latex(R3))

A4 = f(R3 @ A3)
b4 = f(R3 @ b3)
print(A4)
print(b4)
print(matrix2latex(A4))
print(matrix2latex(b4))

[[   1.        0.        0.        0.    ]
 [   0.        1.        0.        0.    ]
 [   0.        0.        1.        0.    ]
 [   0.        0.     -163.8333    1.    ]]

        \begin{array}{cccc}
               1 &    0 &    0 &    0 \\    0 &    1 &    0 &    0 \\    0 &    0 &    1 &    0 \\    0 &    0 & -163.833 &    1
        \end{array}
    
[[ 4.09600e-01  1.23400e-01  3.67800e-01  2.94300e-01]
 [ 0.00000e+00  3.19500e-01  1.99800e-01 -4.85000e-02]
 [ 0.00000e+00  0.00000e+00 -6.00000e-04 -1.85100e-01]
 [ 0.00000e+00  0.00000e+00 -0.00000e+00  3.06426e+01]]
[[  0.4043]
 [ -0.0667]
 [  0.0814]
 [-13.6955]]

        \begin{array}{cccc}
            0.4096 & 0.1234 & 0.3678 & 0.2943 \\    0 & 0.3195 & 0.1998 & -0.0485 \\    0 &    0 & -0.0006 & -0.1851 \\    0 &    0 &   -0 & 30.6426
        \end{array}
    

        \begin{array}{c}
            0.4043 \\ -0.0667 \\ 0.0814 \\ -13.6955
        \end{array}
    


In [54]:
x = np.zeros((4,))
x[3] = f(b4[3] / A4[3][3])
print(x)
x[2] = f((b4[2] - A4[2][3] * x[3]) / A4[2][2])
print(x)
x[1] = f((b4[1] - A4[1][3] * x[3] - A4[1][2] * x[2]) / A4[1][1])
print(x)
x[0] = f((b4[0] - A4[0][3] * x[3] - A4[0][2] * x[2] - A4[0][1] * x[1]) / A4[0][0])
print(x)


[ 0.      0.      0.     -0.4469]
[ 0.      0.      2.202  -0.4469]
[ 0.     -1.6536  2.202  -0.4469]
[-0.1709 -1.6536  2.202  -0.4469]


In [62]:
A = np.array([
    [0.4096, 0.1234, 0.3678, 0.2943],
    [0.2246, 0.3872, 0.4015, 0.1129],
    [0.3645, 0.1920, 0.3781, 0.0643],
    [0.1784, 0.4002, 0.2786, 0.3927]
])
b = np.array([
    [0.4043],
    [0.1550],
    [0.4240],
    [-0.2557]
])
print(A)
print(b)

[[0.4096 0.1234 0.3678 0.2943]
 [0.2246 0.3872 0.4015 0.1129]
 [0.3645 0.192  0.3781 0.0643]
 [0.1784 0.4002 0.2786 0.3927]]
[[ 0.4043]
 [ 0.155 ]
 [ 0.424 ]
 [-0.2557]]


In [63]:
R = np.array([
    [1., 0., 0., 0.],
    [-A[1][0] / A[0][0], 1., 0., 0.],
    [-A[2][0] / A[0][0], 0., 1., 0.],
    [-A[3][0] / A[0][0], 0., 0., 1.]
])

f = round_n(4)
R = f(R)

print(R)
print(matrix2latex(R))

A2 = f(R @ A)
b2 = f(R @ b)

print(A2)
print(b2)

[[ 1.      0.      0.      0.    ]
 [-0.5483  1.      0.      0.    ]
 [-0.8899  0.      1.      0.    ]
 [-0.4355  0.      0.      1.    ]]

        \begin{array}{cccc}
               1 &    0 &    0 &    0 \\ -0.5483 &    1 &    0 &    0 \\ -0.8899 &    0 &    1 &    0 \\ -0.4355 &    0 &    0 &    1
        \end{array}
    
[[ 0.4096  0.1234  0.3678  0.2943]
 [ 0.      0.3195  0.1998 -0.0485]
 [-0.      0.0822  0.0508 -0.1976]
 [ 0.      0.3465  0.1184  0.2645]]
[[ 0.4043]
 [-0.0667]
 [ 0.0642]
 [-0.4318]]


In [64]:
P2 = np.array([
    [1., 0., 0., 0.],
    [0., 0., 0., 1.],
    [0., 0., 1., 0.],
    [0., 1., 0., 0.]
])
A2 = P2 @ A2
b2 = P2 @ b2
print(A2)
print(b2)

[[ 0.4096  0.1234  0.3678  0.2943]
 [ 0.      0.3465  0.1184  0.2645]
 [ 0.      0.0822  0.0508 -0.1976]
 [ 0.      0.3195  0.1998 -0.0485]]
[[ 0.4043]
 [-0.4318]
 [ 0.0642]
 [-0.0667]]


In [65]:
print(matrix2latex(P2))


        \begin{array}{cccc}
               1 &    0 &    0 &    0 \\    0 &    0 &    0 &    1 \\    0 &    0 &    1 &    0 \\    0 &    1 &    0 &    0
        \end{array}
    


In [66]:
R2 = np.array([
    [1., 0., 0., 0.],
    [0., 1., 0., 0.],
    [0., -A2[2][1] / A2[1][1], 1., 0.],
    [0., -A2[3][1] / A2[1][1], 0., 1.]
])
R2 = f(R2)
print(R2)
print(matrix2latex(R2))
A2 = f(R2 @ A2)
b2 = f(R2 @ b2)
print(A2)
print(b2)

[[ 1.      0.      0.      0.    ]
 [ 0.      1.      0.      0.    ]
 [ 0.     -0.2372  1.      0.    ]
 [ 0.     -0.9221  0.      1.    ]]

        \begin{array}{cccc}
               1 &    0 &    0 &    0 \\    0 &    1 &    0 &    0 \\    0 & -0.2372 &    1 &    0 \\    0 & -0.9221 &    0 &    1
        \end{array}
    
[[ 0.4096  0.1234  0.3678  0.2943]
 [ 0.      0.3465  0.1184  0.2645]
 [ 0.      0.      0.0227 -0.2603]
 [ 0.     -0.      0.0906 -0.2924]]
[[ 0.4043]
 [-0.4318]
 [ 0.1666]
 [ 0.3315]]


In [67]:
P3 = np.array([
    [1., 0., 0., 0.],
    [0., 1., 0., 0.],
    [0., 0., 0., 1.],
    [0., 0., 1., 0.]
])
print(matrix2latex(P3))
A3 = P3 @ A2
b3 = P3 @ b2 
print(A3)
print(b3)



        \begin{array}{cccc}
               1 &    0 &    0 &    0 \\    0 &    1 &    0 &    0 \\    0 &    0 &    0 &    1 \\    0 &    0 &    1 &    0
        \end{array}
    
[[ 0.4096  0.1234  0.3678  0.2943]
 [ 0.      0.3465  0.1184  0.2645]
 [ 0.      0.      0.0906 -0.2924]
 [ 0.      0.      0.0227 -0.2603]]
[[ 0.4043]
 [-0.4318]
 [ 0.3315]
 [ 0.1666]]


In [68]:
R3 = np.array([
    [1., 0., 0., 0.],
    [0., 1., 0., 0.],
    [0., 0., 1., 0.],
    [0., 0., -A3[3][2] / A3[2][2], 1.]
])
R3 = f(R3)
print(R3)
print(matrix2latex(R3))
A4 = f(R3 @ A3)
b4 = f(R3 @ b3)
print(A4)
print(b4)
print(matrix2latex(A4))
print(matrix2latex(b4))

[[ 1.      0.      0.      0.    ]
 [ 0.      1.      0.      0.    ]
 [ 0.      0.      1.      0.    ]
 [ 0.      0.     -0.2506  1.    ]]

        \begin{array}{cccc}
               1 &    0 &    0 &    0 \\    0 &    1 &    0 &    0 \\    0 &    0 &    1 &    0 \\    0 &    0 & -0.2506 &    1
        \end{array}
    
[[ 0.4096  0.1234  0.3678  0.2943]
 [ 0.      0.3465  0.1184  0.2645]
 [ 0.      0.      0.0906 -0.2924]
 [ 0.      0.     -0.     -0.187 ]]
[[ 0.4043]
 [-0.4318]
 [ 0.3315]
 [ 0.0835]]

        \begin{array}{cccc}
            0.4096 & 0.1234 & 0.3678 & 0.2943 \\    0 & 0.3465 & 0.1184 & 0.2645 \\    0 &    0 & 0.0906 & -0.2924 \\    0 &    0 &   -0 & -0.187
        \end{array}
    

        \begin{array}{c}
            0.4043 \\ -0.4318 \\ 0.3315 \\ 0.0835
        \end{array}
    


In [69]:
x = np.zeros((4,))
x[3] = f(b4[3] / A4[3][3])
print(x)
x[2] = f((b4[2] - A4[2][3] * x[3]) / A4[2][2])
print(x)
x[1] = f((b4[1] - A4[1][3] * x[3] - A4[1][2] * x[2]) / A4[1][1])
print(x)
x[0] = f((b4[0] - A4[0][3] * x[3] - A4[0][2] * x[2] - A4[0][1] * x[1]) / A4[0][0])
print(x)

[ 0.      0.      0.     -0.4465]
[ 0.      0.      2.2179 -0.4465]
[ 0.     -1.6632  2.2179 -0.4465]
[-0.1826 -1.6632  2.2179 -0.4465]


In [70]:
print(A)
print(b)

[[0.4096 0.1234 0.3678 0.2943]
 [0.2246 0.3872 0.4015 0.1129]
 [0.3645 0.192  0.3781 0.0643]
 [0.1784 0.4002 0.2786 0.3927]]
[[ 0.4043]
 [ 0.155 ]
 [ 0.424 ]
 [-0.2557]]


In [73]:
x = np.array([-0.1709, -1.6536,  2.2020,  -0.4469]).reshape(-1, )
x1 = np.array([-0.1826, -1.6632,  2.2179, -0.4465]).reshape(-1, 1)
print(x)
print(x1)
e = A @ x - b 
e1 = A @ x1 - b
print(e)
print(e1)
print(np.linalg.norm(e), np.linalg.norm(e1))

[-0.1709 -1.6536  2.202  -0.4469]
[[-0.1826]
 [-1.6632]
 [ 2.2179]
 [-0.4465]]
[[ 1.8050000e-05 -2.4931007e-01  1.9756280e-02 -6.5857971e-01]
 [ 2.4931805e-01 -1.0070000e-05  2.6905628e-01 -4.0927971e-01]
 [-1.9681950e-02 -2.6901007e-01  5.6280000e-05 -6.7827971e-01]
 [ 6.6001805e-01  4.1068993e-01  6.7975628e-01  1.4202900e-03]]
[[ 6.830e-06]
 [ 7.400e-05]
 [-1.406e-05]
 [ 7.791e-05]]
1.5483899821328344 0.00010858315062676791


In [96]:
A = np.array([
    [0.6428, 0.3475, -0.8468],
    [0.3475, 1.8423, 0.4759],
    [-0.8468, 0.4759, 1.2147]
])
b = np.array([
    [0.4127],
    [1.7321],
    [-0.8621]
])
print(A)
print(b)
print(matrix2latex(A))
print(matrix2latex(b))

[[ 0.6428  0.3475 -0.8468]
 [ 0.3475  1.8423  0.4759]
 [-0.8468  0.4759  1.2147]]
[[ 0.4127]
 [ 1.7321]
 [-0.8621]]

        \left[\begin{array}{ccc}
            0.6428 & 0.3475 & -0.8468 \\ 0.3475 & 1.8423 & 0.4759 \\ -0.8468 & 0.4759 & 1.2147
        \end{array}\right]
    

        \left[\begin{array}{c}
            0.4127 \\ 1.7321 \\ -0.8621
        \end{array}\right]
    


In [97]:
from scipy.linalg import lu 
P, L, U = lu(A)
print(matrix2latex(P))
print(matrix2latex(L))
print(matrix2latex(U))


        \left[\begin{array}{ccc}
              0 &   0 &   1 \\   0 &   1 &   0 \\   1 &   0 &   0
        \end{array}\right]
    

        \left[\begin{array}{ccc}
              1 &   0 &   0 \\ -0.410368 &   1 &   0 \\ -0.759093 & 0.347838 &   1
        \end{array}\right]
    

        \left[\begin{array}{ccc}
            -0.8468 & 0.4759 & 1.2147 \\   0 & 2.03759 & 0.974375 \\   0 &   0 & -0.263654
        \end{array}\right]
    


In [95]:
# Ax = b
# PAx = Pb
# LUx = Pb
# x = U^-1 L^-1 L U x = U^-1 L^-1 P b
x = np.linalg.inv(U) @ np.linalg.inv(L) @ P @ b 
print(x)
print(matrix2latex(x))
print(A @ x - b)

[[ 4.58668603]
 [-0.63152317]
 [ 2.73520014]]

        \left[\begin{array}{c}
            4.58669 \\ -0.631523 \\ 2.7352
        \end{array}\right]
    
[[3.88578059e-16]
 [4.44089210e-16]
 [3.33066907e-16]]


<img src='./temp1.png'>

In [103]:
A = np.array([
    [2., 1., -3., -1.],
    [3., 1., 0., 7.],
    [-1., 2., 4., -2.],
    [1., 0., -1., 5.]
])
print(A)

P, L, U = lu(A)
P = np.linalg.inv(P)
print(P)
print(L)
print(U)
L_ = np.linalg.inv(L)
U_ = np.linalg.inv(U)
print(L_)
print(U_)
print(matrix2latex(P))
print(matrix2latex(L_))
print(matrix2latex(U_))

[[ 2.  1. -3. -1.]
 [ 3.  1.  0.  7.]
 [-1.  2.  4. -2.]
 [ 1.  0. -1.  5.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
[[ 1.          0.          0.          0.        ]
 [-0.33333333  1.          0.          0.        ]
 [ 0.66666667  0.14285714  1.          0.        ]
 [ 0.33333333 -0.14285714  0.12        1.        ]]
[[ 3.          1.          0.          7.        ]
 [ 0.          2.33333333  4.          0.33333333]
 [ 0.          0.         -3.57142857 -5.71428571]
 [ 0.          0.          0.          3.4       ]]
[[ 1.          0.          0.          0.        ]
 [ 0.33333333  1.          0.          0.        ]
 [-0.71428571 -0.14285714  1.          0.        ]
 [-0.2         0.16       -0.12        1.        ]]
[[ 0.33333333 -0.14285714 -0.16       -0.94117647]
 [ 0.          0.42857143  0.48        0.76470588]
 [-0.         -0.         -0.28       -0.47058824]
 [ 0.          0.          0.          0.29411765]]

        \left[\begin{array}{cccc}
       

In [105]:
print(P @ A - L @ U)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.11471052e-17 0.00000000e+00 0.00000000e+00]]


In [107]:
print(matrix2latex(A))

A_ = (U_) @ (L_) @ P 
print(85 * A_)
print(A_ @ A)
print(matrix2latex(85 * A_))


        \left[\begin{array}{cccc}
               2 &    1 &   -3 &   -1 \\    3 &    1 &    0 &    7 \\   -1 &    2 &    4 &   -2 \\    1 &    0 &   -1 &    5
        \end{array}\right]
    
[[ -4.  50. -23. -80.]
 [ 33. -30.  41.  65.]
 [-19.  25.  -3. -40.]
 [ -3.  -5.   4.  25.]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00 -6.66133815e-16]
 [ 1.11022302e-16  1.00000000e+00  1.11022302e-16  3.33066907e-16]
 [ 0.00000000e+00  1.38777878e-17  1.00000000e+00  2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

        \left[\begin{array}{cccc}
              -4 &   50 &  -23 &  -80 \\   33 &  -30 &   41 &   65 \\  -19 &   25 &   -3 &  -40 \\   -3 &   -5 &    4 &   25
        \end{array}\right]
    


In [92]:
print(A)
print(P @ A)
print(L_ @ P @ A)

[[ 2.  1. -3. -1.]
 [ 3.  1.  0.  7.]
 [-1.  2.  4. -2.]
 [ 1.  0. -1.  5.]]
[[-1.  2.  4. -2.]
 [ 2.  1. -3. -1.]
 [ 3.  1.  0.  7.]
 [ 1.  0. -1.  5.]]
[[-1.          2.          4.         -2.        ]
 [ 1.66666667  1.66666667 -1.66666667 -1.66666667]
 [ 3.42857143 -0.57142857 -2.42857143  8.57142857]
 [ 1.16       -0.36       -2.28        4.4       ]]


In [111]:
from scipy.linalg import schur

A = np.array([
    [1., 2., 3.],
    [2., 3., 4.],
    [-1., 0., 0.]
])
print(A)
ATA = A.T @ A
T, Z = schur(ATA)
print(Z)
print(T)
print(np.trace(ATA), np.trace(T))

[[ 1.  2.  3.]
 [ 2.  3.  4.]
 [-1.  0.  0.]]
[[ 0.34522186  0.93704257  0.05266009]
 [ 0.54914188 -0.15617376 -0.82100728]
 [ 0.76109465 -0.31234752  0.56848391]]
[[ 4.29767316e+01  3.46978577e-17  2.11994168e-15]
 [ 0.00000000e+00  1.00000000e+00 -1.64594839e-16]
 [ 0.00000000e+00  0.00000000e+00  2.32684051e-02]]
44.0 44.000000000000014


In [119]:
Q = np.array([
    [1./2., 3.**0.5 / 2.],
    [3.**0.5 / 2., -1./2.]
])
print(Q)
D = np.array([
    [4., 0.],
    [0., 1.]
])
A = Q @ D @ Q.T 
print(A)

T, Z = schur(A)
print(T)
print(Z)

[[ 0.5        0.8660254]
 [ 0.8660254 -0.5      ]]
[[1.75       1.29903811]
 [1.29903811 3.25      ]]
[[1. 0.]
 [0. 4.]]
[[-0.8660254 -0.5      ]
 [ 0.5       -0.8660254]]


In [124]:
W = Z @ (T ** 0.5)
print(W)

print(np.linalg.eigvals(W.T@W))

[[-0.8660254  -1.        ]
 [ 0.5        -1.73205081]]
[1. 4.]
