In [2]:
import numpy as np

In [5]:
def matrix2latex(A: np.array, n: int = 4):
    n, m = A.shape[:2]
    newline = r' \\ '
    command = f"""
        \\left[\\begin{{array}}{{{"c"*m}}}
            {(newline.join(" & ".join('{:{}g}'.format(A[i][j], n) for j in range(m)) for i in range(n)))}
        \\end{{array}}\\right]
    """
    return command

def valid_n(n: int):
    valid_number_n = lambda x : float(np.format_float_scientific(x, n, True))
    return np.vectorize(valid_number_n)

def round_n(n: int):
    valid_number_n = lambda x : round(x, n)
    return np.vectorize(valid_number_n)

f = valid_n(3 - 1)
A = np.random.random((4, 4)) * 5
print(A)
print(f(A))

[[1.71607104 2.25029047 1.50265432 3.8973375 ]
 [0.09159829 0.90764985 2.72764998 0.74138953]
 [4.0612882  4.87472565 0.94341931 4.44177951]
 [1.01275467 3.38762489 4.27224021 4.68089014]]
[[1.72   2.25   1.5    3.9   ]
 [0.0916 0.908  2.73   0.741 ]
 [4.06   4.87   0.943  4.44  ]
 [1.01   3.39   4.27   4.68  ]]


In [31]:
def Jacobi_Gauss_Seidel(A, b):
    n = A.shape[0]
    L, U, D = np.tril(A, -1), np.triu(A, 1), np.diag(np.diag(A))
    L, U = -L, -U 

    B1 = np.linalg.inv(D) @ (L + U)
    f1 = np.linalg.inv(D) @ b

    B2 = np.linalg.inv(D - L) @ U 
    f2 = np.linalg.inv(D - L) @ b 

    return ((B1, f1), (B2, f2))

A = np.array([ 
    [5, 2, 1],
    [-1, 4, 2],
    [2, -3, 10]
])
b = np.array([
    [-12],
    [20],
    [3]
])

def Rho(A, display=True):
    eigval = np.linalg.eigvals(A)
    if display:
        print(eigval)
    return np.max(eigval * np.conj(eigval)) ** 0.5

(B, f), (G, g) = Jacobi_Gauss_Seidel(A, b)
print(matrix2latex(B))
print(matrix2latex(f))
print(matrix2latex(G))
print(matrix2latex(g))

print(Rho(B), Rho(G))



        \left[\begin{array}{ccc}
              0 & -0.4 & -0.2 \\ 0.25 &   0 & -0.5 \\ -0.2 & 0.3 &   0
        \end{array}\right]
    

        \left[\begin{array}{c}
            -2.4 \\   5 \\ 0.3
        \end{array}\right]
    

        \left[\begin{array}{ccc}
              0 & -0.4 & -0.2 \\   0 & -0.1 & -0.55 \\   0 & 0.05 & -0.125
        \end{array}\right]
    

        \left[\begin{array}{c}
            -2.4 \\ 4.4 \\ 2.1
        \end{array}\right]
    
[-0.21474642+0.j         0.10737321+0.4945574j  0.10737321-0.4945574j]
[ 0.    +0.j         -0.1125+0.16535946j -0.1125-0.16535946j]
(0.5060790704799386+0j) (0.2+0j)


In [33]:
def Iter(x, B, f, norm=None, eps=1e-3, max_iter=1000):
    if norm is None:
        norm = lambda x0 : np.max(np.abs(x0))
    iter = 0
    while iter < max_iter:
        iter += 1
        x_ = B @ x + f
        # print(iter)
        # print(x)
        # print(x_) 
        if norm(x_ - x) < eps:
            return x_
        else:
            x = x_ 

x1 = Iter(x=np.zeros_like(b), B=B, f=f, eps=1e-4)
x2 = Iter(x=np.zeros_like(b), B=G, f=g, eps=1e-4)
print(x1)
print(x2)

print(matrix2latex(x1))
print(matrix2latex(x2))



[[-3.99999642]
 [ 2.99997389]
 [ 1.99999989]]
[[-4.00003333]
 [ 2.99998307]
 [ 2.00000159]]

        \left[\begin{array}{c}
             -4 \\ 2.99997 \\   2
        \end{array}\right]
    

        \left[\begin{array}{c}
            -4.00003 \\ 2.99998 \\   2
        \end{array}\right]
    


In [25]:
A4 = np.array([
    [1., 0.4, 0.4],
    [0.4, 1., 0.8],
    [0.4, 0.8, 1.]
])
b4 = np.array([
    [1.],
    [2.],
    [3.]
])
print(matrix2latex(A4))
print(matrix2latex(b4))

(B4, f4), (G4, g4) = Jacobi_Gauss_Seidel(A4, b)

print(B4)
print(G4)

print(matrix2latex(B4))
print(matrix2latex(G4))

print(Rho(B4), Rho(G4))

print(Rho(A4))


        \left[\begin{array}{ccc}
              1 & 0.4 & 0.4 \\ 0.4 &   1 & 0.8 \\ 0.4 & 0.8 &   1
        \end{array}\right]
    

        \left[\begin{array}{c}
              1 \\   2 \\   3
        \end{array}\right]
    
[[ 0.  -0.4 -0.4]
 [-0.4  0.  -0.8]
 [-0.4 -0.8  0. ]]
[[ 0.    -0.4   -0.4  ]
 [ 0.     0.16  -0.64 ]
 [ 0.     0.032  0.672]]

        \left[\begin{array}{ccc}
              0 & -0.4 & -0.4 \\ -0.4 &   0 & -0.8 \\ -0.4 & -0.8 &   0
        \end{array}\right]
    

        \left[\begin{array}{ccc}
              0 & -0.4 & -0.4 \\   0 & 0.16 & -0.64 \\   0 & 0.032 & 0.672
        \end{array}\right]
    
[ 0.29282032 -1.09282032  0.8       ]
[0.         0.20373601 0.62826399]
1.0928203230275508 0.6282639865827456
[0.70717968 2.09282032 0.2       ]
2.092820323027551


In [34]:
A8 = np.array([
    [1., 0., -1/4, -1/4],
    [0., 1., -1/4, -1/4],
    [-1/4, -1/4, 1., 0.],
    [-1/4, -1/4, 0., 1.]
])
b8 = np.array([1/2, 1/2, 1/2, 1/2]).reshape(-1, 1)
print(matrix2latex(A8))
print(matrix2latex(b8))

(B8, f8), (G8, g8) = Jacobi_Gauss_Seidel(A8, b8)
# print(B8)
# print(f8)
# print(matrix2latex(B8))
# print(matrix2latex(f8))
# print(Rho(B8))
print(G8)
print(g8)
print(matrix2latex(G8))
print(matrix2latex(b8))
print(Rho(G8))



        \left[\begin{array}{cccc}
               1 &    0 & -0.25 & -0.25 \\    0 &    1 & -0.25 & -0.25 \\ -0.25 & -0.25 &    1 &    0 \\ -0.25 & -0.25 &    0 &    1
        \end{array}\right]
    

        \left[\begin{array}{c}
             0.5 \\  0.5 \\  0.5 \\  0.5
        \end{array}\right]
    
[[0.    0.    0.25  0.25 ]
 [0.    0.    0.25  0.25 ]
 [0.    0.    0.125 0.125]
 [0.    0.    0.125 0.125]]
[[0.5 ]
 [0.5 ]
 [0.75]
 [0.75]]

        \left[\begin{array}{cccc}
               0 &    0 & 0.25 & 0.25 \\    0 &    0 & 0.25 & 0.25 \\    0 &    0 & 0.125 & 0.125 \\    0 &    0 & 0.125 & 0.125
        \end{array}\right]
    

        \left[\begin{array}{c}
             0.5 \\  0.5 \\  0.5 \\  0.5
        \end{array}\right]
    
[0.00000000e+00 0.00000000e+00 2.50000000e-01 2.77555756e-17]
0.25


In [40]:
def SOR(A, b, x=None, omega=1.0, norm=None, x_=None, eps=1e-4, max_iter=1000, show_details=False):
    if show_details:
        print(f'omega = {omega}')
        print("=======================")

    if norm is None:
        norm = lambda x0 : np.max(np.abs(x0))
    
    if x is None:
        x = np.zeros_like(b)

    L, U, D = np.tril(A, -1), np.triu(A, 1), np.diag(np.diag(A))
    L, U = -L, -U 
    
    T = np.linalg.inv(D - omega * L)
    B = T @ ((1. - omega) * D + omega * U)
    f = omega * T @ b

    iter = 0
    while iter < max_iter:
        iter += 1
        x1 = B @ x + f 
        if x_ is None:
            err = norm(x1 - x)
        else:
            err = norm(x1 - x_)
        if show_details:
            print(iter)
            print(x1) 
            print(err)
            print("=======================")
        if err < eps:
            return x1 
        else:
            x = x1  
    return x

A = np.array([
    [4., -1., 0.],
    [-1., 4., -1.],
    [0., -1., 4.]
])
b = np.array([1., 4., -3.]).reshape(-1, 1)

print(matrix2latex(A))
print(matrix2latex(b))

x = SOR(A, b, omega=1.03, x_=np.array([0.5, 1., -0.5]).reshape(-1, 1), eps=5e-6, show_details=True)
print(x)
x = SOR(A, b, omega=1., x_=np.array([0.5, 1., -0.5]).reshape(-1, 1), eps=5e-6, show_details=True)
print(x)
x = SOR(A, b, omega=1.1, x_=np.array([0.5, 1., -0.5]).reshape(-1, 1), eps=5e-6, show_details=True)
print(x)
                



        \left[\begin{array}{ccc}
              4 &  -1 &   0 \\  -1 &   4 &  -1 \\   0 &  -1 &   4
        \end{array}\right]
    

        \left[\begin{array}{c}
              1 \\   4 \\  -3
        \end{array}\right]
    
omega = 1.03
1
[[ 0.2575    ]
 [ 1.09630625]
 [-0.49020114]]
0.2425
2
[[ 0.53207386]
 [ 1.00789304]
 [-0.49826151]]
0.03207385937500007
3
[[ 0.50107024]
 [ 1.00048646]
 [-0.49992689]]
0.001070241395117133
4
[[ 0.50009316]
 [ 1.00002822]
 [-0.49999493]]
9.315558142797276e-05
5
[[ 0.50000447]
 [ 1.00000161]
 [-0.49999974]]
4.47176785400849e-06
[[ 0.50000447]
 [ 1.00000161]
 [-0.49999974]]
omega = 1.0
1
[[ 0.25    ]
 [ 1.0625  ]
 [-0.484375]]
0.25
2
[[ 0.515625  ]
 [ 1.0078125 ]
 [-0.49804688]]
0.015625
3
[[ 0.50195312]
 [ 1.00097656]
 [-0.49975586]]
0.001953125
4
[[ 0.50024414]
 [ 1.00012207]
 [-0.49996948]]
0.000244140625
5
[[ 0.50003052]
 [ 1.00001526]
 [-0.49999619]]
3.0517578125e-05
6
[[ 0.50000381]
 [ 1.00000191]
 [-0.49999952]]
3.814697265625e-06
[[ 0.50000381

In [3]:
import numpy as np

x = np.linspace(-4.5, 4.5, 10)
print(x)
y = 1. / (1. + x * x)
print(y)
z = 0.5 / (1. + (x - 0.5) * (x - 0.5)) + 0.5 / (1. + (x + 0.5) * (x + 0.5))
print(z)

[-4.5 -3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5  4.5]
[0.04705882 0.0754717  0.13793103 0.30769231 0.8        0.8
 0.30769231 0.13793103 0.0754717  0.04705882]
[0.04864253 0.07941176 0.15       0.35       0.75       0.75
 0.35       0.15       0.07941176 0.04864253]
